---
- hosts: all
  roles:
    - vagrant
  vars:
    gitconfig_users:
      - user: vagrant
        name: Vagrant User
        email: info@example.com
        push_default: upstream
        ignore_github:
          - Linux
          - Vim
        ignore_custom: |
          .vagrant
          *.bak
