---
- name: ensure git is configured for users
  template: src=git-config.j2
            dest="/home/{{ item.user }}/.gitconfig"
            owner="{{ item.user }}" group="{{ item.user }}" mode=0644
  with_items: gitconfig_users

- name: ensure gitignore directory for users exists
  file: dest="/home/{{ item.user }}/.gitignore-sources"
        state=directory
        owner="{{ item.user }}" group="{{ item.user }}" mode=0755
  when: item.ignore_github is defined or item.ignore_custom is defined
  with_items: gitconfig_users

- name: ensure gitignore source files from github.com for users are installed
  get_url: url="https://raw.githubusercontent.com/github/gitignore/master/Global/{{ item[1] }}.gitignore"
           dest="/home/{{ item[0].user }}/.gitignore-sources/{{ item[1] }}.gitignore"
           owner="{{ item[0].user }}" group="{{ item[0].user }}" mode=0644
  with_subelements:
    - gitconfig_users
    - ignore_github

- name: ensure custom gitignore source file for users is installed
  copy: content="{{ item.ignore_custom }}"
        dest="/home/{{ item.user }}/.gitignore-sources/custom.gitignore"
        owner="{{ item.user }}" group="{{ item.user }}" mode=0644
  when: item.ignore_custom is defined
  with_items: gitconfig_users

- name: ensure gitignore files for users are assembled
  assemble: src="/home/{{ item.user }}/.gitignore-sources"
            dest="/home/{{ item.user }}/.gitignore"
            owner="{{ item.user }}" group="{{ item.user }}" mode=0644
  when: item.ignore_github is defined or item.ignore_custom is defined
  with_items: gitconfig_users
